[dev] Monorepo: consolidate ci-workflow (include changelog/md-files validation) (#52398)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,6 @@
 name: 'CI'
 on:
   pull_request:
-    paths-ignore:
-      - 'docs/**'
-      - '**/changelog/**'
-      - '**/*.md'
   push:
     paths-ignore:
       - 'docs/**'
@@ -32,27 +28,55 @@ env:
   FORCE_COLOR: 1
 
 jobs:
+  identify-jobs-to-run:
+    name: 'Analyze changes'
+    if: ${{ !cancelled() && github.event_name == 'pull_request' }}
+    runs-on: 'ubuntu-20.04'
+    outputs:
+      needs-code-validation: ${{ steps.target-changes.outputs.needs-code-validation }}
+      needs-changelog-validation: ${{ steps.target-changes.outputs.needs-changelog-validation }}
+      needs-markdown-validation:  ${{ steps.target-changes.outputs.needs-markdown-validation }}
+    steps:
+      - uses: 'dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36'
+        id: target-changes
+        with:
+          filters: |
+            needs-code-validation:
+              - '!((**/*.md)|(**/changelog/*))'
+            needs-changelog-validation:
+              - '{packages,plugins}/*/!(changelog/**)/**'
+            needs-markdown-validation:
+              - '!(.github/**)/**/*.md'
+
   project-jobs:
     # Since this is a monorepo, not every pull request or change is going to impact every project.
     # Instead of running CI tasks on all projects indiscriminately, we use a command to detect
     # which projects have changed and what kind of change occurred. This lets us build the
     # matrices that we can use to run CI tasks only on the projects that need them.
     name: 'Build Project Jobs'
+    if: ${{ !cancelled() }}
+    needs: 'identify-jobs-to-run'
     runs-on: 'ubuntu-20.04'
     outputs:
       lint-jobs: ${{ steps.project-jobs.outputs.lint-jobs }}
       test-jobs: ${{ steps.project-jobs.outputs.test-jobs }}
       report-jobs: ${{ steps.project-jobs.outputs.report-jobs }}
     steps:
-      - uses: 'actions/checkout@v4'
-        name: 'Checkout'
+      - name: Setup - calculate checkout depth
+        id: checkout_depth
+        shell: bash
+        run: |
+          pull_request_commits=$(( ${{ ( github.event_name == 'pull_request' && github.event.pull_request.commits ) || 1 }} + 1 ))
+          echo "pull_request_commits=$pull_request_commits" >> $GITHUB_OUTPUT
+      - name: Setup - checkout
+        uses: 'actions/checkout@v4'
         with:
-          # If 'base_ref' is available, the 'Build Matrix' step requires non-shallow git-history to identify changed files.
-          fetch-depth: ${{ ( ( github.base_ref && '0' ) || '1' ) }}
-      - name: 'Setup PNPM'
+          ref: ${{ ( github.event_name == 'pull_request' && github.head_ref ) || '' }}
+          fetch-depth: ${{ steps.checkout_depth.outputs.pull_request_commits }}
+      - name: Setup - pnpm
         uses: 'pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d'
-      - uses: actions/github-script@v7
-        name: 'Build Matrix'
+      - name: Setup - spawn linting and testing jobs
+        uses: actions/github-script@v7
         id: 'project-jobs'
         with:
           script: |
@@ -60,10 +84,11 @@ jobs:
             // - PRs: run CI jobs aiming PRs and filter out jobs based on the content changes
             // - Pushes: run CI jobs aiming pushes without filtering based on the content changes
 
-            // github.base_ref is only available for pull_request events
-            let baseRef = ${{ toJson( github.base_ref ) }};
-            if ( baseRef ) {
-              baseRef = `--base-ref origin/${ baseRef }`;
+            let baseRef   = '';
+            const baseSha = ${{ toJson( github.event.pull_request.base.sha ) }};
+            if ( baseSha ) {
+              // Use-case: trigger is pull request
+              baseRef = `--base-ref ${ baseSha }`;
             }
 
             let githubEvent = ${{ toJson( github.event_name ) }};
@@ -94,23 +119,28 @@ jobs:
             child_process.execSync( `pnpm utils ci-jobs ${ baseRef } --event ${ githubEvent }` );
 
   project-lint-jobs:
-    name: "Lint - ${{ matrix.projectName }} ${{ matrix.optional && ' (optional)' || ''}}"
+    name: "Lint - ${{ matrix.projectName }} ${{ ( matrix.optional && ' (optional)' ) || '' }}"
     runs-on: 'ubuntu-20.04'
     needs: 'project-jobs'
-    if: ${{ needs.project-jobs.outputs.lint-jobs != '[]' && github.event_name == 'pull_request' }}
+    if: ${{ !cancelled() && github.event_name == 'pull_request' && needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' && needs.project-jobs.outputs.lint-jobs != '[]' }}
     strategy:
       fail-fast: false
       matrix:
         include: ${{ fromJSON( needs.project-jobs.outputs.lint-jobs ) }}
     steps:
+      - name: 'Calculate checkout depth'
+        id: checkout_depth
+        shell: bash
+        run: |
+          pull_request_commits=$(( ${{ github.event.pull_request.commits }} + 1 ))
+          echo "pull_request_commits=$pull_request_commits" >> $GITHUB_OUTPUT
+
       - uses: 'actions/checkout@v4'
-        name: 'Checkout'
         with:
-          # the WooCommerce plugin package uses phpcs-changed for linting, which requires non-shallow git-history.
-          fetch-depth: ${{ ( ( matrix.projectName == '@woocommerce/plugin-woocommerce' && '0' ) || '1' ) }}
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: ${{ steps.checkout_depth.outputs.pull_request_commits }}
 
       - uses: './.github/actions/setup-woocommerce-monorepo'
-        name: 'Setup Monorepo'
         id: 'setup-monorepo'
         with:
           install: '${{ matrix.projectName }}...'
@@ -123,7 +153,7 @@ jobs:
     name: '${{ matrix.name }}'
     runs-on: 'ubuntu-20.04'
     needs: 'project-jobs'
-    if: ${{ needs.project-jobs.outputs.test-jobs != '[]' }}
+    if: ${{ !cancelled() && ( github.event_name != 'pull_request' || needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' ) && needs.project-jobs.outputs.test-jobs != '[]' }}
     env: ${{ matrix.testEnv.envVars }}
     strategy:
       fail-fast: false
@@ -267,7 +297,7 @@ jobs:
     # on the results of the other jobs in the workflow.
     name: 'Evaluate Project Job Statuses'
     runs-on: 'ubuntu-20.04'
-    needs: ['project-jobs', 'project-lint-jobs', 'project-test-jobs']
+    needs: [ 'identify-jobs-to-run', 'project-jobs', 'project-lint-jobs', 'project-test-jobs', 'validate-changelog', 'validate-markdown' ]
     if: ${{ !cancelled() && github.event_name == 'pull_request' }}
     steps:
       - uses: 'actions/checkout@v4'
@@ -279,7 +309,7 @@ jobs:
           RUN_ID: ${{ github.run_id }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # Check if project-jobs was successful. Fail for any other status, including skipped. 
+          # Check if project-jobs was successful. Fail for any other status, including skipped.
           result="${{ needs.project-jobs.result }}"
           if [[ $result != "success" ]]; then
             echo "Generating CI jobs was not successful."
@@ -323,7 +353,7 @@ jobs:
   test-reports:
     name: 'Test reports - ${{ matrix.report }}'
     needs: ['project-jobs', 'project-test-jobs']
-    if: ${{ !cancelled() && needs.project-jobs.outputs.report-jobs != '[]' && github.repository == 'woocommerce/woocommerce' }}
+    if: ${{ !cancelled() && github.repository == 'woocommerce/woocommerce' && ( github.event_name != 'pull_request' || needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' ) && needs.project-jobs.outputs.report-jobs != '[]' }}
     strategy:
       fail-fast: false
       matrix:
@@ -380,7 +410,7 @@ jobs:
 
   report-flaky-tests:
     name: 'Create issues for flaky tests'
-    if: ${{ !cancelled() && github.repository == 'woocommerce/woocommerce' && needs.project-jobs.outputs.test-jobs != '[]' }}
+    if: ${{ !cancelled() && github.repository == 'woocommerce/woocommerce' && ( github.event_name != 'pull_request' || needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' ) && needs.project-jobs.outputs.test-jobs != '[]' }}
     needs: ['project-jobs', 'project-test-jobs']
     runs-on: ubuntu-latest
     permissions:
@@ -412,3 +442,185 @@ jobs:
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           label: 'metric: flaky e2e test'
+
+  validate-changelog:
+    name: 'Validate changelog'
+    if: ${{ !cancelled() && github.event_name == 'pull_request' && needs.identify-jobs-to-run.outputs.needs-changelog-validation == 'true' }}
+    needs: [ 'identify-jobs-to-run', 'project-jobs' ]
+    runs-on: 'ubuntu-20.04'
+    permissions:
+      contents: read
+
+    steps:
+      - name: 'Calculate checkout depth'
+        id: checkout_depth
+        shell: bash
+        run: |
+          pull_request_commits=$(( ${{ github.event.pull_request.commits }} + 1 ))
+          echo "pull_request_commits=$pull_request_commits" >> $GITHUB_OUTPUT
+
+      - uses: 'actions/checkout@v4'
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: ${{ steps.checkout_depth.outputs.pull_request_commits }}
+
+      - uses: './.github/actions/setup-woocommerce-monorepo'
+        with:
+          # The package has majority of composer-deps, therefore referencing it
+          pull-package-composer-deps: '@woocommerce/plugin-woocommerce'
+
+      - name: 'Validate - missing entries'
+        env:
+          BASE: ${{ github.event.pull_request.base.sha }}
+          HEAD: ${{ github.event.pull_request.head.sha }}
+        run: php tools/monorepo/check-changelogger-use.php --debug "$BASE" "$HEAD"
+
+      - name: 'Validate - existing entries'
+        run: pnpm --recursive --parallel --stream changelog validate
+
+  validate-markdown:
+    name: 'Validate markdown'
+    if: ${{ !cancelled() && github.event_name == 'pull_request' && needs.identify-jobs-to-run.outputs.needs-markdown-validation == 'true' }}
+    needs: [ 'identify-jobs-to-run', 'project-jobs' ]
+    runs-on: 'ubuntu-20.04'
+    permissions:
+      contents: read
+
+    steps:
+      - name: 'Calculate checkout depth'
+        id: checkout_depth
+        shell: bash
+        run: |
+          pull_request_commits=$(( ${{ github.event.pull_request.commits }} + 1 ))
+          echo "pull_request_commits=$pull_request_commits" >> $GITHUB_OUTPUT
+
+      - uses: 'actions/checkout@v4'
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: ${{ steps.checkout_depth.outputs.pull_request_commits }}
+
+      - name: Scan - markdown files from monorepo packages
+        id: repo-changed-files
+        uses: tj-actions/changed-files@v41
+        with:
+          files: |
+            **/*.md
+          files_ignore: |
+            docs/**/*.md
+            .github/**/*.md
+
+      - name: Scan - markdown files from monorepo documentation
+        id: docs-changed-files
+        uses: tj-actions/changed-files@v41
+        with:
+          files: |
+            docs/**/*.md
+
+      - name: Scan - manifest files for monorepo documentation
+        id: docs-manifest
+        uses: tj-actions/changed-files@v41
+        with:
+          files: |
+            docs/docs-manifest.json
+
+      - name: Setup - pnpm
+        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
+
+      - name: Setup - node
+        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
+        with:
+          node-version-file: .nvmrc
+          cache: pnpm
+          registry-url: 'https://registry.npmjs.org'
+
+      - name: Setup - utility-packages
+        run: |
+          pnpm i -g markdownlint-cli
+          npm --prefix .github/workflows/scripts install @actions/core
+
+      - name: Validate - changed markdown files from monorepo documentation
+        run: |
+          RED="\e[1;31m"
+          GREEN="\e[1;32m"
+          NC="\e[0m"
+          set -e
+          rc=0
+          changed_files="${{ steps.repo-changed-files.outputs.all_changed_files  }}"
+          if [ -n "$changed_files" ]; then
+            lint_results=""
+            for file in $changed_files; do
+              lint_result=$( { cat "$file" | markdownlint --stdin ; } 2>&1 ) || rc="$?"
+              if [ $rc -ne 0 ]; then
+                lint_results="$lint_results\n>>>Linting failed for file: $file <<<\n$lint_result\n--------"
+              fi
+            done
+            if [ $rc -ne 0 ]; then
+              echo -e "${RED}Linting failed for one or more files${NC}"
+              echo -e "$lint_results"
+              exit 1
+            else
+              echo -e "${GREEN}Linting successful for all files.${NC}"
+            fi
+          else
+            echo "No repo markdown files changed."
+          fi
+
+      - name: Validate - manifest files for monorepo documentation
+        id: is-valid-json
+        run: node .github/workflows/scripts/is-valid-json.js docs/docs-manifest.json
+
+      - name: Validate - changed markdown files from monorepo documentation
+        run: |
+          RED="\e[1;31m"
+          GREEN="\e[1;32m"
+          NC="\e[0m"
+          set -e
+          rc=0
+          changed_files="${{ steps.docs-changed-files.outputs.all_changed_files }}"
+          changed_manifest="${{ steps.docs-manifest.outputs.all_changed_files }}"
+          is_valid_json="${{ steps.is-valid-json.outputs.is-valid-json }}"
+          storybook="no"
+          for L in ${{github.event.pull_request.labels.*.name}}
+          do
+            if [ $L == "type: storybook" ]; then
+              storybook="yes"
+            fi
+          done
+          if [ -n "$changed_files" ]; then
+            lint_results=""
+            failed_check=""
+            for file in $changed_files; do
+              lint_result=$( { cat "$file" | markdownlint --stdin -c docs/.markdownlint.json ; } 2>&1 ) || rc="$?"
+              if [ $rc -ne 0 ]; then
+                lint_results="$lint_results\n>>>Linting failed for file: $file <<<\n$lint_result\n--------"
+              fi
+            done
+          
+            if [ $rc -ne 0 ]; then
+              echo -e "${RED}Linting failed for one or more files${NC}"
+              echo -e "$lint_results"
+              failed_check="lint"
+            else
+              echo -e "${GREEN}Linting successful for all files.${NC}"
+            fi
+          
+            if [ "$storybook" == "no" ]; then
+              if [ -z "$changed_manifest" ]; then
+                echo -e "${RED}Changes in the docs folder require updating the manifest${NC}"
+                failed_check="manifest"
+              fi
+              if [ "$is_valid_json" == "no" ]; then
+                echo -e "${RED}'docs/docs-manifest.json' is not valid JSON${NC}"
+                failed_check="manifest"
+              fi
+              if [ "$failed_check" == "manifest" ]; then
+                echo -e "Generate a manifest with 'pnpm utils md-docs create docs woocommerce -o docs/docs-manifest.json'"
+              fi
+            fi
+          
+            if [ -n "$failed_check" ]; then
+              exit 1
+            fi
+          else
+            echo "No docs markdown files changed."
+          fi
